### PR TITLE
Add Lithos

### PR DESCRIPTION
**Pull request by jirutka**

### CODE REVIEW

**Comment by Friz-zy** [comment]
Hi, thank you
Can you move it into `Hypervisors` section please?

**Comment by jirutka** [comment]
When I compare projects in Hypervisors and Containers sections, I don’t think that lithos belongs to the Hypervisors section. It’s not some management tool that uses some container runner like runc.

**Comment by Friz-zy** [comment]
"Lithos is a process supervisor and containerizer for running services" - this is definitely what I mean for `Hypervisors` section. Docker also doesn't manage anything except it's own containers...

**Comment by jirutka** [comment]
Docker uses runc for running containers. Anyway, it just shows that these sections are not very accurate… I’ll move it to the Hypervisors section.

**Comment by jirutka** [comment]
Done.

**Comment by Friz-zy** [comment]
`runc` is actually just a part of docker engine, docker just was splitted into many parts from one single app, nothing else. `runc` can't run anything except docker image format which became a base for the OCS spec

Thanks

**Pull request merged**
