### PR TITLE
Moved OpenVZ from hypervisors to containers, added CRIU project

### PR DESCRIPTION
**Pull request by ligurio**

### CODE REVIEW

**Comment by Friz-zy** [comment]
OpenVZ utils can create checkpoints and can control all containers from root.
In my opinion - it's a hypervisor's signs...
Can you explain your point of view?
By the way, thanks for good products ;)

**Comment by ligurio** [comment]
Container virtualization is a OS level virtualization: you customize host operating system to get isolated multiple environments. In case of OpenVZ we create network, PID, mount, UTS namespaces to isolate container from each other and host OS itself. This type of virtualization requires customizing of each subsystem which you want "virtualize". But in most cases namespaces from list above is more than enough.

In case hypervisor-based virtualization (other name is "hardware"-based virtualization you have a special piece of software (hypervisor or vmm) which manage virtual machines. In that case modification of OS in environment is not mandatory (but preferred for performance purposes) and you get full isolation from host OS.

**Comment by Friz-zy** [comment]
Oh, i know basics.
This is list of container virtualization only, so 'hypervisor' - it's daemon or tool that can spawn and manage containers for many users. Don't treat it in the traditional model of virtual machines.

**Comment by Friz-zy** [comment]
CRIU added in 647e5b5219476af5ec204d51ce52c53f50ec0cb7
Thank you

**Pull request closed without merging**
