### PR TITLE
add docker-pushrm, a Docker CLI plugin that that lets you push the RE…

### PR DESCRIPTION
**Pull request by christian-korneck**
…ADME.md file from the current directory to a container registry like Docker Hub.

### CODE REVIEW

**Comment by christian-korneck** [comment]
Dear maintainers, did you have a chance to review my PR yet? Thanks!

**Comment by christian-korneck** [comment]
Any news?

**Comment by Friz-zy** [comment]
Sorry for delay xD
Thank you :)

**Comment by christian-korneck** [comment]
thanks!

**Pull request merged**
